name: '68 Pictures, LLC'
favicon: null
layout_spectrum: 0.03355668345466256
typography_spectrum: 0.17800819361582398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.48960790876299143
  lightness: 0.3917677835561335
  saturation: 0.6601100324187428
  rhythmicContrast: 0.029091344913467765
purpose: []
